#!/bin/bash
GIT_SERVER=git.corp.airties.com                                                                                                                            
REFERENCES_PATH=$(git config --global references.path)
DOMAIN_USER_NAME=$(git config --global --get user.email | sed 's/\(.*\)@.*/\1/')

[ -z $1 ] && REPOSITORY=buildsys || REPOSITORY=$1
[ -z $2 ] && DESTINATION_PATH=$REPOSITORY || DESTINATION_PATH=$2

if [ ! -z $REFERENCES_PATH ]
then
  if [ -d $REFERENCES_PATH/$REPOSITORY.git ]
  then
    git --git-dir=$REFERENCES_PATH/$REPOSITORY.git fetch
  else
    git clone --mirror git://git.corp.airties.com/$REPOSITORY $REFERENCES_PATH/$REPOSITORY.git
  fi
  REFERENCES_PARAM="--reference $REFERENCES_PATH/$REPOSITORY.git"
fi

git clone $REFERENCES_PARAM git://git.corp.airties.com/$REPOSITORY $DESTINATION_PATH

[ -z $DOMAIN_USER_NAME ] || git --git-dir=$DESTINATION_PATH/.git remote set-url --push origin ssh://$DOMAIN_USER_NAME@$GIT_SERVER:29418/$REPOSITORY
