#!/usr/bin/expect


spawn /home/noe/DataDrive/reSystem/scripts/gh.sh

expect -exact "Username for 'https://github.com':"
send -- "noe287\r"
expect -exact "Password for 'https://noe287@github.com':"
send -- "noe287287\r"

expect -exact "Username for 'https://github.com':"
send -- "noe287\r"
expect -exact "Password for 'https://noe287@github.com':"
send -- "noe287287\r"

expect -exact "eof" 

